app:
  name: gitpuk

server:
  port: 8090

APP_HOME: ${APP_HOME}

#DATA config
DATA_HOME: ${user.home}/tiklab/gitpuk

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab-gitpuk?stringtype=unspecified
  username: postgres
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: true
  database: gitpuk_ce
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200


#(local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: http://eas-ce.demo.tiklab.net
  expire: 86400 # 过期时间，单位秒，默认1天

external:
  url:


gitPuk:
  ssh:
    port: 10000
    key: tiklab-gitpuk-starter/file/id_rsa
  file: tiklab-gitpuk-starter/file
