app:
  name: thoughtware-gittok
  version: ce

APP_HOME: ${APP_HOME}
application: gittok

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

gittok:
  ssh:
    port: 10000
    key: thoughtware-gittok-starter/file/id_rsa
  file: thoughtware-gittok-starter/file


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/thoughtware_gittok?stringtype=unspecified
  username: postgres
  password: darth2020



#plugin config
DATA_HOME: /opt/tiklab/thoughtware_gittok
plugin:
  path: ${DATA_HOME}/plugin

postgresql:
  embbed:
    enable: true
  database: thoughtware_gittok
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.thoughtware.cn

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches



message:
  sms:
    enabled: true

base:
  url: http://eas-ce.demo.thoughtware.cn


#homes
homes:
  address: http://homes.thoughtware.cn

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net



repository:
  address: ${DATA_HOME}/repository



visit:
  address: http://gittok-ce.demo.thoughtware.cn

backups:
  time: 0 0 2 * * ?
  dir: /data
  xcode:
    dir: ${DATA_HOME}/repository


