app:
  name: thoughtware-gitpuk
  version: ce

APP_HOME: ${APP_HOME}
application: gitpuk

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8090

gitPuk:
  ssh:
    port: 10001
    key: thoughtware-gitpuk-starter/file/id_rsa
  file: thoughtware-gitpuk-starter/file


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5431/gitpuk_ce?stringtype=unspecified
  username: postgres
  password: darth2020


#plugin config
DATA_HOME: /opt/thoughtware/gitpuk_ce


plugin:
  path: ${DATA_HOME}/plugin

postgresql:
  embbed:
    enable: true
  database: gitpuk_ce
  db:
    port: 5431
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

soular:
  embbed:
    enable: true


#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6001
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6001
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches



message:
  sms:
    enabled: true

base:
  url: http://e.eas.thoughtware.net


#homes
homes:
  address: http://homes.tiklab.net

#license
licences:
  path: ${DATA_HOME}/licences

#file
file:
  path: http://file.tiklab.net



repository:
  address: ${DATA_HOME}/repository



visit:
  address: http://e.gitpuk.tiklab.net

backups:
  time: 0 0 2 * * ?
  dir: /data
  xcode:
    dir: ${DATA_HOME}/repository