app:
  name: tiklab-gitpuk

server:
  port: 8090

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab-gitpuk?stringtype=unspecified
  username: postgres
  #driverClassName: com.mysql.cj.jdbc.Driver
  #url: jdbc:mysql://172.10.1.10:3306/tiklab_gitpuk?characterEncoding=utf8&useSSL=false
  #username: root
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: false
  type: local
  database: tiklab-gitpuk


#(local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: http://192.168.10.15:8080
    web:
      address: http://192.168.10.16:3010
  expire: 86400 # 过期时间，单位秒，默认1天
#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

external:
  url:


gitPuk:
  ssh:
    port: 10055
    key: tiklab-gitpuk-starter/file/id_rsa
  file: tiklab-gitpuk-starter/file


