app:
  name: tiklab-gitpuk

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false

server:
  port: 8090

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  #url: jdbc:postgresql://172.10.1.10:5432/tiklab-gitpuk?stringtype=unspecified
  url: jdbc:postgresql://172.10.1.10:5432/thoughtware-gittok?stringtype=unspecified
  #url: jdbc:postgresql://172.13.1.23:5432/xcode_ee?stringtype=unspecified
  username: postgres
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: false
  type: local
  database: tiklab-gitpuk

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: true

message:
  sms:
    enabled: true

gitPuk:
  ssh:
    port: 10003
    key: tiklab-gitpuk-starter/file/id_rsa
  file: tiklab-gitpuk-starter/file

base:
  url: http://192.168.10.9:8090

repository:
  address: ${DATA_HOME}/repository

#license
licences:
  path: ${DATA_HOME}/licences


backups:
  time: 0 0 2 * * ?
  dir: /data
  xcode:
    dir: ${DATA_HOME}/repository

visit:
  address: ""

spotbugs:
  address: /embbed/spotbugs-4.8.1/bin

postin:
  scan:
    package: io.tiklab.gitpuk
