app:
  name: thoughtware-gittok
  version: ce

APP_HOME: ${APP_HOME}
application: gitpuk

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

gitPuk:
  ssh:
    port: 10000
    key: thoughtware-gitpuk-starter/file/id_rsa
  file: thoughtware-gitpuk-starter/file


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/thoughtware_gittok?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: thoughtware_gittok
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


DATA_HOME: /opt/thoughtware/gittok

plugin:
  path: ${DATA_HOME}/plugin



soular:
  embbed:
    enable: false
  address: http://e.tiklab.net

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${DATA_HOME}/caches



message:
  sms:
    enabled: true

base:
  address: http://e.eas.tiklab.net

  #homes
homes:
  address: http://homes.tiklab.net


#license
licences:
  path: ${DATA_HOME}/licences

#file
file:
  path: http://file.thoughtware.net

repository:
  address: ${DATA_HOME}/repository

backups:
  time: 0 0 2 * * ?
  dir: /data
  xcode:
    dir: ${DATA_HOME}/repository

visit:
  address: ""









