app:
  name: gitpuk

spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    checkTemplateLocation: false

server:
  port: 8090

APP_HOME: ${APP_HOME}

#DATA config
DATA_HOME: ${user.home}/tiklab/gitpuk

#database config
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tiklab_gittpuk?stringtype=unspecified
  username: postgres
  password: darth2020

# Enable the embedded database
postgresql:
  embbed:
    enable: true
  database: tiklab_gittpuk
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net


# repository  config
repository:
  address: ${DATA_HOME}/repository

gitPuk:
  ssh:
    port: 10000
    key: tiklab-gitpuk-starter/file/id_rsa
  file: tiklab-gitpuk-starter/file


# git clone path
visit:
  address: http://gitpuk-ce.demo.tiklab.net


spotbugs:
  address: /embbed/spotbugs-4.8.1/bin

base:
  url: http://eas-ce.demo.tiklab.net

#license
licences:
  path: ${DATA_HOME}/licences

backups:
  time: 0 0 2 * * ?
  dir: /data
  xcode:
    dir: ${DATA_HOME}/repository


postin:
  scan:
    package: io.tiklab.gitpuk